FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

CMD ["celery", "-A", "gestion_escolar", "worker", "--loglevel=INFO"]
