# Generated by Django 5.2.8 on 2025-11-28 05:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('NORMAL', 'Asignatura regular'), ('TALLER', 'Taller'), ('REFUERZO', 'Refuerzo'), ('LIBRE', 'Libre disposición')], default='NORMAL', max_length=20)),
                ('carga_horaria_semanal', models.PositiveIntegerField(default=2, help_text='Horas pedagógicas semanales asignadas.')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviar_despues_de', models.DateTimeField(blank=True, help_text='Fecha/hora a partir de la cual puede enviarse el correo.', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('ultimo_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Correo en cola',
                'verbose_name_plural': 'Correos en cola',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre interno del período (Ej: 2025 - Semestre 1).', max_length=100)),
                ('anio', models.PositiveIntegerField(help_text='Año académico (Ej: 2025).')),
                ('tipo', models.CharField(choices=[('ANUAL', 'Anual'), ('SEMESTRAL', 'Semestral'), ('TRIMESTRAL', 'Trimestral'), ('BIMESTRAL', 'Bimestral')], default='ANUAL', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True, help_text='Indica si es el período activo actual.')),
            ],
            options={
                'verbose_name': 'Período académico',
                'verbose_name_plural': 'Períodos académicos',
                'ordering': ['-anio', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('SALA_CLASE', 'Sala de clases'), ('LABORATORIO', 'Laboratorio'), ('BIBLIOTECA', 'Biblioteca'), ('TALLER', 'Taller'), ('OTRO', 'Otro')], default='SALA_CLASE', max_length=20)),
                ('capacidad', models.PositiveIntegerField(default=40)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('recursos_basicos', models.TextField(blank=True, help_text='Descripción breve de recursos disponibles (proyector, audio, computadores, etc.).')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('archivo', models.FileField(upload_to='adjuntos/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_adjuntos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo adjunto',
                'verbose_name_plural': 'Archivos adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del curso (Ej: 7°A, 2°B).', max_length=50)),
                ('nivel', models.CharField(blank=True, help_text='Nivel educativo (Ej: 7° Básico, 2° Medio).', max_length=50)),
                ('capacidad_maxima', models.PositiveIntegerField(default=45, help_text='Capacidad máxima de estudiantes.')),
                ('estudiantes', models.ManyToManyField(blank=True, help_text='Estudiantes matriculados en este curso.', related_name='cursos_estudiante', to=settings.AUTH_USER_MODEL)),
                ('jefe_curso', models.ForeignKey(blank=True, help_text='Docente jefe de curso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_jefe', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(help_text='Período académico al que pertenece el curso.', on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='academico.periodoacademico')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['periodo', 'nombre'],
                'unique_together': {('nombre', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='AlertaTemprana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('NOTAS', 'Notas'), ('DISCIPLINA', 'Disciplina'), ('MIXTO', 'Mixto')], max_length=20)),
                ('descripcion', models.TextField()),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=20)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_SEGUIMIENTO', 'En seguimiento'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_creadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_tempranas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_tempranas', to='academico.curso')),
            ],
            options={
                'verbose_name': 'Alerta temprana',
                'verbose_name_plural': 'Alertas tempranas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('PRUEBA', 'Prueba'), ('TAREA', 'Tarea'), ('PROYECTO', 'Proyecto'), ('EXAMEN', 'Examen'), ('OTRO', 'Otro')], default='PRUEBA', max_length=20)),
                ('fecha_evaluacion', models.DateField()),
                ('fecha_limite_publicacion', models.DateField(help_text='Fecha límite institucional para publicar las notas.')),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATRASADA', 'Atrasada'), ('PUBLICADA', 'Publicada')], default='PENDIENTE', max_length=20)),
                ('ponderacion', models.DecimalField(decimal_places=2, default=0, help_text='Ponderación de la evaluación dentro del promedio (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='academico.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academico.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_docente', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='academico.periodoacademico')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACADEMICA', 'Académica'), ('CONVIVENCIA', 'Convivencia escolar'), ('TARDANZA', 'Atrasos'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('gravedad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='BAJA', max_length=20)),
                ('descripcion', models.TextField()),
                ('requiere_seguimiento', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones', to='academico.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('resultado', models.TextField(blank=True)),
                ('alerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones', to='academico.alertatemprana')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones_responsable', to=settings.AUTH_USER_MODEL)),
                ('observacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones', to='academico.observacion')),
            ],
            options={
                'verbose_name': 'Intervención',
                'verbose_name_plural': 'Intervenciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloques_horarios', to='academico.periodoacademico')),
            ],
            options={
                'verbose_name': 'Bloque horario',
                'verbose_name_plural': 'Bloques horarios',
                'ordering': ['periodo', 'dia_semana', 'hora_inicio'],
                'unique_together': {('periodo', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='ReporteNotasPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/notas/pdf/')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/notas/excel/')),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_notas', to='academico.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_notas', to='academico.curso')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_notas_generados', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_notas', to='academico.periodoacademico')),
            ],
            options={
                'verbose_name': 'Reporte de notas por período',
                'verbose_name_plural': 'Reportes de notas por período',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ReunionApoderados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Individual (por alumno)'), ('GRUPAL', 'Grupal (por curso)')], default='INDIVIDUAL', max_length=20)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('temas_tratados', models.TextField()),
                ('acuerdos', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('apoderado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones_apoderado', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones', to='academico.curso')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones_docente', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(blank=True, help_text='Aplicable en reuniones individuales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reunión con apoderados',
                'verbose_name_plural': 'Reuniones con apoderados',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MinutaReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título o encabezado de la minuta.', max_length=200)),
                ('resumen_general', models.TextField(help_text='Resumen general de los temas tratados en la reunión.')),
                ('acuerdos_detallados', models.TextField(blank=True, help_text='Detalle de acuerdos, compromisos y responsables.')),
                ('compromisos_apoderados', models.TextField(blank=True, help_text='Compromisos asumidos por apoderados.')),
                ('compromisos_establecimiento', models.TextField(blank=True, help_text='Compromisos asumidos por el establecimiento (docentes, UTP, dirección, etc.).')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales o comentarios relevantes.')),
                ('archivo_pdf', models.FileField(blank=True, help_text='Versión en PDF de la minuta (opcional).', null=True, upload_to='reuniones/minutas/pdf/')),
                ('creada_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la minuta.')),
                ('actualizada_en', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización de la minuta.')),
                ('autor', models.ForeignKey(blank=True, help_text='Usuario que redactó la minuta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutas_reunion_autor', to=settings.AUTH_USER_MODEL)),
                ('reunion', models.ForeignKey(help_text='Reunión a la que pertenece esta minuta.', on_delete=django.db.models.deletion.CASCADE, related_name='minutas', to='academico.reunionapoderados')),
            ],
            options={
                'verbose_name': 'Minuta de reunión',
                'verbose_name_plural': 'Minutas de reuniones',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('sala', models.ForeignKey(blank=True, help_text='Sala donde se encuentra el recurso (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='academico.sala')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('ATRASO', 'Atraso'), ('JUSTIFICADO', 'Ausencia justificada')], max_length=20)),
                ('motivo_inasistencia', models.TextField(blank=True, help_text='Motivo si el estudiante estuvo ausente o con atraso.')),
                ('es_justificada', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(blank=True, help_text='Opcional: asistencia por asignatura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='academico.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.curso')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha'],
                'unique_together': {('estudiante', 'curso', 'fecha', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, help_text='Nota en escala 1.0 a 7.0.', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)])),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(default='MANUAL', help_text='Origen del registro (MANUAL, EXCEL, IMPORTADO).', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.evaluacion')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-fecha_registro'],
                'unique_together': {('evaluacion', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='PromedioFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)])),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios_finales', to='academico.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios_finales', to='academico.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios_finales', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promedios_finales', to='academico.periodoacademico')),
            ],
            options={
                'verbose_name': 'Promedio final',
                'verbose_name_plural': 'Promedios finales',
                'unique_together': {('estudiante', 'curso', 'asignatura', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaReunionApoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=False)),
                ('justificacion', models.TextField(blank=True)),
                ('temas_tratados', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_reuniones', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_reuniones_estudiante', to=settings.AUTH_USER_MODEL)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_apoderados', to='academico.reunionapoderados')),
            ],
            options={
                'verbose_name': 'Asistencia a reunión de apoderado',
                'verbose_name_plural': 'Asistencias a reuniones de apoderados',
                'unique_together': {('reunion', 'apoderado', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='HorarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_rotativo', models.BooleanField(default=False, help_text='Indica si este horario corresponde a una rotación especial dentro del período.')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='academico.asignatura')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_bloque', to='academico.bloquehorario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_docente', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='academico.periodoacademico')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_sala', to='academico.sala')),
            ],
            options={
                'verbose_name': 'Horario de curso',
                'verbose_name_plural': 'Horarios de curso',
                'ordering': ['curso', 'bloque'],
                'unique_together': {('curso', 'asignatura', 'docente', 'sala', 'bloque', 'periodo')},
            },
        ),
    ]
