# Generated by Django 5.2.8 on 2025-11-25 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 2025', max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Año académico',
                'verbose_name_plural': 'Años académicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('horas_semanales', models.PositiveIntegerField(default=2)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Educación Básica', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('capacidad', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 1° Básico A', max_length=50)),
                ('anio_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academico.anioacademico')),
                ('profesor_jefe', models.ForeignKey(blank=True, limit_choices_to={'role__code': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_jefe', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='academico.nivel')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['anio_academico', 'nombre'],
                'unique_together': {('anio_academico', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='AsignaturaCursoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignatura', to='academico.asignatura')),
                ('docente', models.ForeignKey(limit_choices_to={'role__code': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_docente', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_curso', to='academico.curso')),
            ],
            options={
                'verbose_name': 'Asignación de asignatura',
                'verbose_name_plural': 'Asignaciones de asignaturas',
                'unique_together': {('curso', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='AlertaTemprana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='BAJO', max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('notificada', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(limit_choices_to={'role__code': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
                ('generada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_generadas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='academico.curso')),
            ],
            options={
                'verbose_name': 'Alerta temprana',
                'verbose_name_plural': 'Alertas tempranas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_destinatario', models.CharField(choices=[('USER', 'Usuario individual'), ('CURSO', 'Curso completo'), ('APODERADOS', 'Apoderados del estudiante')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('enviado', models.BooleanField(default=False)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.curso')),
                ('destinatario_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correo en cola',
                'verbose_name_plural': 'Correos en cola',
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACADEMICA', 'Académica'), ('DISCIPLINARIA', 'Disciplinaria')], max_length=20)),
                ('gravedad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='BAJA', max_length=10)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('resuelta', models.BooleanField(default=False)),
                ('resolucion', models.TextField(blank=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones', to='academico.curso')),
                ('estudiante', models.ForeignKey(limit_choices_to={'role__code': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to=settings.AUTH_USER_MODEL)),
                ('registrada_por', models.ForeignKey(limit_choices_to={'role__code__in': ['DOCENTE', 'DIRECTOR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'ordering': ['-fecha', 'estudiante'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Primer Semestre', max_length=50)),
                ('tipo', models.CharField(choices=[('SEM', 'Semestre'), ('OTRO', 'Otro')], default='SEM', max_length=10)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='academico.anioacademico')),
            ],
            options={
                'verbose_name': 'Periodo académico',
                'verbose_name_plural': 'Periodos académicos',
                'ordering': ['anio', 'orden'],
                'unique_together': {('anio', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRUEBA', 'Prueba'), ('EXAMEN', 'Examen'), ('TAREA', 'Tarea'), ('TRABAJO', 'Trabajo'), ('OTRO', 'Otro')], default='PRUEBA', max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('ponderacion', models.DecimalField(decimal_places=2, help_text='Peso de esta evaluación en el promedio del periodo (ej: 20.00 = 20%)', max_digits=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academico.asignaturacursodocente')),
                ('creado_por', models.ForeignKey(limit_choices_to={'role__code': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='academico.periodoacademico')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReunionApoderados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tema', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='academico.curso')),
                ('docente', models.ForeignKey(limit_choices_to={'role__code': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reunión de apoderados',
                'verbose_name_plural': 'Reuniones de apoderados',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('ATRASO', 'Atraso'), ('JUSTIFICADO', 'Ausencia justificada')], max_length=20)),
                ('justificacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.asignatura')),
                ('estudiante', models.ForeignKey(limit_choices_to={'role__code': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(limit_choices_to={'role__code__in': ['DOCENTE', 'ADMIN', 'DIRECTOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.curso')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'curso'],
                'unique_together': {('estudiante', 'curso', 'asignatura', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'role__code': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(limit_choices_to={'role__code': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.evaluacion')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('evaluacion', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado'), ('EGRESADO', 'Egresado')], default='ACTIVO', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('anio_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academico.anioacademico')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academico.curso')),
                ('estudiante', models.ForeignKey(limit_choices_to={'role__code': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('estudiante', 'curso', 'anio_academico')},
            },
        ),
        migrations.CreateModel(
            name='PromedioFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculado_en', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios_finales', to='academico.asignaturacursodocente')),
                ('estudiante', models.ForeignKey(limit_choices_to={'role__code': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='promedios_finales', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promedios_finales', to='academico.periodoacademico')),
            ],
            options={
                'verbose_name': 'Promedio final',
                'verbose_name_plural': 'Promedios finales',
                'unique_together': {('estudiante', 'asignacion', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='ReporteNotasPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_general', models.DecimalField(decimal_places=2, max_digits=5)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'role__code': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_periodo', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='academico.periodoacademico')),
            ],
            options={
                'verbose_name': 'Reporte de notas por periodo',
                'verbose_name_plural': 'Reportes de notas por periodo',
                'unique_together': {('estudiante', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaReunionApoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('apoderado', models.ForeignKey(limit_choices_to={'role__code': 'APODERADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='reuniones_asistidas', to=settings.AUTH_USER_MODEL)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='academico.reunionapoderados')),
            ],
            options={
                'verbose_name': 'Asistencia reunión apoderados',
                'verbose_name_plural': 'Asistencias reuniones apoderados',
                'unique_together': {('reunion', 'apoderado')},
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horario', to='academico.asignaturacursodocente')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques', to='academico.sala')),
            ],
            options={
                'verbose_name': 'Bloque horario',
                'verbose_name_plural': 'Bloques horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('asignacion', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
