# Generated by Django 5.0.14 on 2025-11-26 20:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre del grupo institucional. Ej: '7°A', 'Docentes Matemática'.", max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción general del grupo.')),
            ],
            options={
                'verbose_name': 'Grupo institucional',
                'verbose_name_plural': 'Grupos institucionales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Código interno del permiso. Ej: 'ver_asistencia'.", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nombre legible del permiso.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Descripción del alcance del permiso.')),
            ],
            options={
                'verbose_name': 'Permiso personalizado',
                'verbose_name_plural': 'Permisos personalizados',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='idx_perm_code')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(blank=True, help_text='RUT del usuario (sin puntos, con guion). Obligatorio para ALUMNO y APODERADO.', max_length=12, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Teléfono principal del usuario.', max_length=20)),
                ('address', models.CharField(blank=True, help_text='Dirección del usuario.', max_length=255)),
                ('gender', models.CharField(blank=True, help_text='Género declarado (opcional).', max_length=20)),
                ('birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento del usuario.', null=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0, help_text='Cantidad de intentos fallidos de inicio de sesión.')),
                ('must_change_password', models.BooleanField(default=False, help_text='Indica si el usuario debe cambiar su contraseña en el próximo inicio de sesión.')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='Última dirección IP registrada en el inicio de sesión.', null=True)),
                ('is_blocked', models.BooleanField(default=False, help_text='Indica si el usuario está bloqueado manualmente.')),
                ('blocked_until', models.DateTimeField(blank=True, help_text='Fecha y hora hasta la cual el usuario se encuentra bloqueado temporalmente.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del usuario.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización del usuario.')),
                ('enrollment_year', models.CharField(blank=True, help_text='Año de ingreso/matrícula del usuario (aplica a alumnos).', max_length=10)),
                ('active', models.BooleanField(default=True, help_text='Indica si el usuario está activo en el sistema institucional.')),
                ('profile_image', models.ImageField(blank=True, help_text='Fotografía de perfil institucional.', null=True, upload_to='profiles/')),
                ('apoderados', models.ManyToManyField(blank=True, help_text='Relación entre alumnos y sus apoderados.', related_name='alumnos', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios_user_permissions', to='auth.permission')),
                ('extra_permissions', models.ManyToManyField(blank=True, help_text='Permisos adicionales específicos para este usuario.', to='usuarios.custompermission')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título breve de la notificación.', max_length=200)),
                ('message', models.TextField(help_text='Contenido de la notificación.')),
                ('level', models.CharField(choices=[('INFO', 'Información'), ('WARN', 'Advertencia'), ('URGENT', 'Urgente')], default='INFO', help_text='Nivel de prioridad de la notificación.', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Indica si el usuario ya ha leído la notificación.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la notificación.')),
                ('user', models.ForeignKey(help_text='Usuario destinatario de la notificación.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ADMIN', 'Administrador'), ('DIRECTOR', 'Director'), ('DOCENTE', 'Docente'), ('ALUMNO', 'Alumno'), ('APODERADO', 'Apoderado')], help_text='Código del rol institucional (ADMIN, DIRECTOR, DOCENTE, ALUMNO, APODERADO).', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción general del rol y sus responsabilidades.')),
                ('hierarchy', models.PositiveIntegerField(default=5, help_text='Nivel jerárquico del rol (1 = más alto, 5 = más bajo).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['hierarchy', 'code'],
                'indexes': [models.Index(fields=['code'], name='idx_role_code')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(help_text='Rol institucional asignado al usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.role'),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Descripción breve de la acción realizada.', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent del navegador o cliente que realizó la acción.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró la acción.')),
                ('user', models.ForeignKey(help_text='Usuario asociado a la acción registrada.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de actividad de usuario',
                'verbose_name_plural': 'Registros de actividad de usuario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='groups_institutional',
            field=models.ManyToManyField(blank=True, help_text='Grupos institucionales a los que pertenece el usuario.', to='usuarios.usergroup'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rut'], name='idx_user_rut'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_user_role'),
        ),
    ]
