# Generated by Django 5.0.14 on 2025-11-26 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Rol institucional asignado al usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.role'),
        ),
    ]
